# Set NVIM as the default editor
export EDITOR='nvim'

# Homebrew setup
export HOMEBREW_BIN="/opt/homebrew/bin"
[[ -f "$HOMEBREW_BIN/brew" ]] && eval "$($HOMEBREW_BIN/brew shellenv)"

# Golang environment
export PATH="$(go env GOPATH)/bin:$PATH"

fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit && compinit

# Zinit Plugin Manager initialization
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[[ ! -d "$ZINIT_HOME" ]] && mkdir -p "$(dirname $ZINIT_HOME)" && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "$ZINIT_HOME/zinit.zsh"
# ZSH plugins setup with Zinit
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions

# Environment configuration for Python, Direnv, Gcloud, and other tools
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$HOME/.jenv/bin:$HOME/.bin:/Users/coletroutman/.local/bin:/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/coletroutman/.rd/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
export VIRTUAL_ENV_DISABLE_PROMPT=1
eval "$(pyenv virtualenv-init -)"
eval "$(direnv hook zsh)"
eval "$(jenv init -)"
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Custom scripts and secrets
export CODE_BASE_REPO="$HOME/code"
eval "$(/Users/coletroutman/code/lifechurch/youversion/apis/tools/yv/bin/yv init -)"
# TODO: put this in a better place
source "$HOME/code/colebasaur/dotfiles/.global.env"
[ -f $HOMEBREW_PREFIX/etc/profile.d/autojump.sh ] && . $HOMEBREW_PREFIX/etc/profile.d/autojump.sh

source ~/.aliases
source ~/.functions

. "$HOME/.atuin/bin/env"

eval "$(atuin init zsh)"
bindkey '^p' atuin-up-search
bindkey '^n' atuin-down-search

# local start_time=$(gdate +%s%N)
eval "$(starship init zsh)"
# local end_time=$(gdate +%s%N)
# echo "Starship init took: $(((end_time - start_time) / 1000000))ms"

. "$HOME/.local/share/../bin/env"
